from __future__ import annotations

from enum import StrEnum


class RunState(StrEnum):
    RUN_STARTED = "run_started"
    CONFIG_LOADED = "config_loaded"
    WORKSPACE_STARTING = "workspace_starting"
    WORKSPACE_READY = "workspace_ready"
    WORKSPACE_DIRTY = "workspace_dirty"
    WORKSPACE_PATCH_CAPTURED = "workspace_patch_captured"
    WORKSPACE_STOPPING = "workspace_stopping"
    WORKSPACE_STOPPED = "workspace_stopped"
    WORKSPACE_RETAINED = "workspace_retained"
    WORKSPACE_CLEANUP_FAILED = "workspace_cleanup_failed"
    AGENT_INITIALIZED = "agent_initialized"
    AGENT_CONTEXT_LOADED = "agent_context_loaded"
    AGENT_ACTING = "agent_acting"
    AGENT_RECOVERING = "agent_recovering"
    AGENT_FINAL_RESULT = "agent_final_result"
    AGENT_HARNESS_REVIEWED = "agent_harness_reviewed"
    REPO_DISCOVERED = "repo_discovered"
    REPO_ELIGIBLE = "repo_eligible"
    REPO_PROFILED = "repo_profiled"
    OPPORTUNITIES_RANKED = "opportunities_ranked"
    TASK_SELECTED = "task_selected"
    WORKSPACE_CHECKED = "workspace_checked"
    CONTRIBUTION_REVIEWED = "contribution_reviewed"
    PR_DRY_RUN_STARTED = "pr_dry_run_started"
    PR_DRAFT_CREATED = "pr_draft_created"
    CI_OBSERVED = "ci_observed"
    POSTMORTEM_WRITTEN = "postmortem_written"
    ARTIFACTS_WRITTEN = "artifacts_written"
    RUN_COMPLETED = "run_completed"
    RUN_TERMINAL = "run_terminal"
    WORKSPACE_FAILED = "workspace_failed"
    GOVERNANCE_BLOCKED = "governance_blocked"
    BUDGET_EXHAUSTED = "budget_exhausted"
    AGENT_ERROR = "agent_error"
